data:
  dataset_path: '../data'
split:
  train: 0.7
  val: 0.15
  test: 0.15
hyperparameters:
  batch_size: 32
  learning_rate: 0.001
  epochs: 20
scheduler:
  step_size: 5
  gamma: 0.1
tensorboard:
  log_dir: '../logs'
model:
  num_classes: 2
  save_dir: '../models'
device: 'cpu'  # or 'cpu'
